name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.5']
    env:
      RACK_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Install tinycdb
        run: sudo apt-get install -y tinycdb libcdb-dev
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run CI task
        run: bundle exec rspec
